export default {
  // Generated by colormind.io
  site_colors: {
    banner:'#2C3D54',
    text:'#131826',
    title:'#B5A280',
    cards:'#D7B47E',
    bg:'#f6f6ef',
    active_link:'#98c5ed'
  }
};
